/** Markdown primitives shared by every reference renderer. */

/**
 * Escape a value for use inside a table cell. Pipes delimit cells, so a value
 * carrying one — `--provider` hints at `openai|anthropic|google` — would
 * otherwise split the row.
 */
export function cell(value: string): string {
  return value.replace(/\|/g, '\\|')
}

/**
 * Escape a source-supplied string for use as rendered prose.
 *
 * `<` starts an HTML tag as far as the markdown renderer is concerned, so a
 * default of `i18n/translate-missing-<timestamp>` renders as
 * `i18n/translate-missing-` with the rest swallowed as an unknown element. Never
 * apply this to a value going inside a code span, where `<` is already literal —
 * a type of `Record<string, string>` must not become `Record&lt;string, string>`.
 */
export function prose(value: string): string {
  return value.replace(/</g, '&lt;')
}

/** Prose inside a table cell: both escapes apply. */
export function textCell(value: string): string {
  return prose(cell(value))
}

export function code(value: string): string {
  return `\`${value}\``
}

export function table(headers: string[], rows: string[][]): string {
  return [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map(row => `| ${row.join(' | ')} |`),
  ].join('\n')
}

/**
 * A YAML frontmatter block. Values are single-quoted with quotes doubled, which
 * is valid YAML for any scalar and keeps a description containing a colon from
 * parsing as a mapping.
 */
export function frontmatter(fields: Record<string, string>): string {
  const lines = Object.entries(fields).map(
    ([key, value]) => `${key}: '${value.replace(/'/g, "''")}'`,
  )
  return ['---', ...lines, '---'].join('\n')
}

/**
 * Marks the file as machine-written for anyone who opens it. An HTML comment
 * rather than prose, so it stays out of the rendered page and out of search.
 */
export const GENERATED_NOTICE
  = '<!-- Generated by docs/generate. Do not edit by hand: change the source '
    + 'definition or the generator, then run `pnpm docs:generate`. -->'

/** Assemble a page from blocks, separated by one blank line and newline-terminated. */
export function page(blocks: (string | undefined)[]): string {
  return `${blocks.filter((block): block is string => Boolean(block)).join('\n\n')}\n`
}
